export interface Country {
  code: string
  name: string
  dial: string
}

export function flag(code: string): string {
  return code.toUpperCase().split('').map(c =>
    String.fromCodePoint(0x1F1E6 + c.charCodeAt(0) - 65)
  ).join('')
}

export const POPULAR_COUNT = 15

export const COUNTRIES: Country[] = [
  // Popular first
  { code: 'US', name: 'United States',          dial: '+1'   },
  { code: 'GB', name: 'United Kingdom',          dial: '+44'  },
  { code: 'CA', name: 'Canada',                  dial: '+1'   },
  { code: 'AU', name: 'Australia',               dial: '+61'  },
  { code: 'DE', name: 'Germany',                 dial: '+49'  },
  { code: 'FR', name: 'France',                  dial: '+33'  },
  { code: 'ES', name: 'Spain',                   dial: '+34'  },
  { code: 'IT', name: 'Italy',                   dial: '+39'  },
  { code: 'BR', name: 'Brazil',                  dial: '+55'  },
  { code: 'MX', name: 'Mexico',                  dial: '+52'  },
  { code: 'IN', name: 'India',                   dial: '+91'  },
  { code: 'CN', name: 'China',                   dial: '+86'  },
  { code: 'JP', name: 'Japan',                   dial: '+81'  },
  { code: 'KR', name: 'South Korea',             dial: '+82'  },
  { code: 'AR', name: 'Argentina',               dial: '+54'  },
  // rest alphabetical
  { code: 'AF', name: 'Afghanistan',             dial: '+93'  },
  { code: 'AL', name: 'Albania',                 dial: '+355' },
  { code: 'DZ', name: 'Algeria',                 dial: '+213' },
  { code: 'AO', name: 'Angola',                  dial: '+244' },
  { code: 'AT', name: 'Austria',                 dial: '+43'  },
  { code: 'AZ', name: 'Azerbaijan',              dial: '+994' },
  { code: 'BD', name: 'Bangladesh',              dial: '+880' },
  { code: 'BE', name: 'Belgium',                 dial: '+32'  },
  { code: 'BO', name: 'Bolivia',                 dial: '+591' },
  { code: 'BA', name: 'Bosnia and Herzegovina',  dial: '+387' },
  { code: 'BG', name: 'Bulgaria',                dial: '+359' },
  { code: 'CM', name: 'Cameroon',                dial: '+237' },
  { code: 'CL', name: 'Chile',                   dial: '+56'  },
  { code: 'CO', name: 'Colombia',                dial: '+57'  },
  { code: 'CD', name: 'DR Congo',                dial: '+243' },
  { code: 'CR', name: 'Costa Rica',              dial: '+506' },
  { code: 'HR', name: 'Croatia',                 dial: '+385' },
  { code: 'CZ', name: 'Czech Republic',          dial: '+420' },
  { code: 'DK', name: 'Denmark',                 dial: '+45'  },
  { code: 'DO', name: 'Dominican Republic',      dial: '+1'   },
  { code: 'EC', name: 'Ecuador',                 dial: '+593' },
  { code: 'EG', name: 'Egypt',                   dial: '+20'  },
  { code: 'ET', name: 'Ethiopia',                dial: '+251' },
  { code: 'FI', name: 'Finland',                 dial: '+358' },
  { code: 'GH', name: 'Ghana',                   dial: '+233' },
  { code: 'GR', name: 'Greece',                  dial: '+30'  },
  { code: 'GT', name: 'Guatemala',               dial: '+502' },
  { code: 'HN', name: 'Honduras',                dial: '+504' },
  { code: 'HK', name: 'Hong Kong',               dial: '+852' },
  { code: 'HU', name: 'Hungary',                 dial: '+36'  },
  { code: 'ID', name: 'Indonesia',               dial: '+62'  },
  { code: 'IR', name: 'Iran',                    dial: '+98'  },
  { code: 'IQ', name: 'Iraq',                    dial: '+964' },
  { code: 'IE', name: 'Ireland',                 dial: '+353' },
  { code: 'IL', name: 'Israel',                  dial: '+972' },
  { code: 'JM', name: 'Jamaica',                 dial: '+1'   },
  { code: 'KZ', name: 'Kazakhstan',              dial: '+7'   },
  { code: 'KE', name: 'Kenya',                   dial: '+254' },
  { code: 'MA', name: 'Morocco',                 dial: '+212' },
  { code: 'MY', name: 'Malaysia',                dial: '+60'  },
  { code: 'NL', name: 'Netherlands',             dial: '+31'  },
  { code: 'NZ', name: 'New Zealand',             dial: '+64'  },
  { code: 'NG', name: 'Nigeria',                 dial: '+234' },
  { code: 'NO', name: 'Norway',                  dial: '+47'  },
  { code: 'PK', name: 'Pakistan',                dial: '+92'  },
  { code: 'PA', name: 'Panama',                  dial: '+507' },
  { code: 'PY', name: 'Paraguay',                dial: '+595' },
  { code: 'PE', name: 'Peru',                    dial: '+51'  },
  { code: 'PH', name: 'Philippines',             dial: '+63'  },
  { code: 'PL', name: 'Poland',                  dial: '+48'  },
  { code: 'PT', name: 'Portugal',                dial: '+351' },
  { code: 'RO', name: 'Romania',                 dial: '+40'  },
  { code: 'RU', name: 'Russia',                  dial: '+7'   },
  { code: 'SA', name: 'Saudi Arabia',            dial: '+966' },
  { code: 'SN', name: 'Senegal',                 dial: '+221' },
  { code: 'ZA', name: 'South Africa',            dial: '+27'  },
  { code: 'SE', name: 'Sweden',                  dial: '+46'  },
  { code: 'CH', name: 'Switzerland',             dial: '+41'  },
  { code: 'TW', name: 'Taiwan',                  dial: '+886' },
  { code: 'TZ', name: 'Tanzania',                dial: '+255' },
  { code: 'TH', name: 'Thailand',                dial: '+66'  },
  { code: 'TR', name: 'Turkey',                  dial: '+90'  },
  { code: 'UA', name: 'Ukraine',                 dial: '+380' },
  { code: 'AE', name: 'United Arab Emirates',    dial: '+971' },
  { code: 'UY', name: 'Uruguay',                 dial: '+598' },
  { code: 'UZ', name: 'Uzbekistan',              dial: '+998' },
  { code: 'VE', name: 'Venezuela',               dial: '+58'  },
  { code: 'VN', name: 'Vietnam',                 dial: '+84'  },
]
